package com.intheeast.jpa;

import lombok.*;

import jakarta.persistence.*;

@Entity
@Setter
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@ToString(exclude = "orderitem")
public class OrderItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private int quantity;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name = "orders_id", nullable = false) // OrderItem 테이블의 FK
    private Order order;
    /*
     create table OrderItem (
       id bigint generated by default as identity,
        quantity integer not null,
        product_id bigint,
        primary key (id)
     )
     alter table OrderItem 
       add constraint FKg23j1vs750x8lkx2aesfk6n2 
       foreign key (product_id) 
       references Product
     */
    

    public OrderItem(Order order, int quantity) {
        this.order = order;
        this.quantity = quantity;
    }
    
    public Long getId() {
    	return this.id;
    }
    
    public int getQuantity() {
    	return this.quantity;
    }
    
    public Order getOrder() {
    	return this.order;
    }

    public void changeOrder(Order newOrder) {
        this.order = newOrder;
    }
}
